// Props of RN 0.87.1's VirtualizedList, FlatList and SectionList that
// ScrollViewProps does not declare. A VirtualizedList spreads its props onto its
// ScrollView, whose native view ignores these; they belong to the list.
export const listOnlyProps = new Set([
  "CellRendererComponent",
  "ItemSeparatorComponent",
  "ListEmptyComponent",
  "ListFooterComponent",
  "ListFooterComponentStyle",
  "ListHeaderComponent",
  "ListHeaderComponentStyle",
  "ListItemComponent",
  "SectionSeparatorComponent",
  "columnWrapperStyle",
  "data",
  "debug",
  "disableVirtualization",
  "extraData",
  "getItem",
  "getItemCount",
  "getItemLayout",
  "initialNumToRender",
  "initialScrollIndex",
  "inverted",
  "keyExtractor",
  "maxToRenderPerBatch",
  "numColumns",
  "onEndReached",
  "onEndReachedThreshold",
  "onRefresh",
  "onScrollToIndexFailed",
  "onStartReached",
  "onStartReachedThreshold",
  "onViewableItemsChanged",
  "progressViewOffset",
  "refreshing",
  "renderItem",
  "renderScrollComponent",
  "renderSectionFooter",
  "renderSectionHeader",
  "sections",
  "stickySectionHeadersEnabled",
  "strictMode",
  "updateCellsBatchingPeriod",
  "viewabilityConfig",
  "viewabilityConfigCallbackPairs",
  "windowSize",
]);
